from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.domain.models import QueueItem, QueueItemCreate


class QueueRepository(Protocol):
    def add(self, item: QueueItemCreate) -> QueueItem: ...

    def add_batch(self, items: list[QueueItemCreate]) -> list[QueueItem]: ...

    def claim(self, run_id: UUID, worker_id: str, limit: int = 10) -> list[QueueItem]: ...

    def complete(self, id: UUID) -> QueueItem: ...

    def fail(self, id: UUID, error: str | None = None) -> QueueItem: ...

    def reset_stale(self, timeout_minutes: int = 5) -> int: ...

    def get_pending_count(self, run_id: UUID) -> int: ...
